#libraries


library(Hmisc)
library(class)
library(gmodels)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(plyr)
library(PerformanceAnalytics)
library(corrplot)
library(caret)
library(xts)
library(zoo)
library(forecast)
library(tseries)
library(arules)
library(FSelectorRcpp)
library(FSelector)
library(remotes)
library(randomForest)
library(stats)
library(rpart.plot)
library(gtools)
library(TANDEM)
library(e1071)
library(pROC)
library(ROCR)
library(C50)




####______________________________________Descriptive Analysis____________________________________



bicycle_theft <- read.csv(file = "bicycle-thefts.csv", header = T, stringsAsFactors = TRUE) #Loading data


bt<- bicycle_theft
bt$event_unique_id<- as.character(bt$event_unique_id)
bt$Occurrence_Date<- as.Date(bt$Occurrence_Date)
bt$Report_Date<- as.Date(bt$Report_Date)
bt$Primary_Offence<- as.character(bt$Primary_Offence)
bt$Occurrence_Year<- as.numeric(bt$Occurrence_Year)
bt$Occurrence_Month<- as.factor(bt$Occurrence_Month)
bt$Occurrence_DayOfWeek<- as.factor(bt$Occurrence_DayOfWeek)
bt$Occurrence_Hour<- as.factor(bt$Occurrence_Hour)
bt$Division<- as.factor(bt$Division)
bt$Hood_ID<- as.integer(bt$Hood_ID)
bt$NeighbourhoodName<- as.character(bt$NeighbourhoodName)
bt$Location_Type<- as.factor(bt$Location_Type)
bt$Premises_Type<- as.factor(bt$Premises_Type)
bt$Bike_Make<- as.character(bt$Bike_Make)
bt$Bike_Model<- as.character(bt$Bike_Model)
bt$Bike_Type<- as.factor(bt$Bike_Type)
bt$Cost_of_Bike<- as.numeric(bt$Cost_of_Bike)
bt$Status<- as.factor(bt$Status)
bt$Bike_Colour<-as.character(bt$Bike_Colour)
str(bt)

#Treating NA's with mean Cost_of_Bike
sum(is.na(bt))
bt$Cost_of_Bike[is.na(bt$Cost_of_Bike)]<- mean(bt$Cost_of_Bike,na.rm=TRUE)

#assinging 2009-2013 year to 2014
bt$Occurrence_Year[bt$Occurrence_Year==2009] <- 2014
bt$Occurrence_Year[bt$Occurrence_Year==2010] <- 2014
bt$Occurrence_Year[bt$Occurrence_Year==2011] <- 2014
bt$Occurrence_Year[bt$Occurrence_Year==2012] <- 2014
bt$Occurrence_Year[bt$Occurrence_Year==2013] <- 2014


###occurrence year
table(bicycle_theft$Occurrence_Year)
summary(bicycle_theft$Occurrence_Year)
boxplot(bicycle_theft$Occurrence_Year, col = "#1763F5", main = "Boxplot of Occurrence Year with Outliers")

table(bt$Occurrence_Year)
boxplot(bt$Occurrence_Year, col = "#F3F515", main = "Boxplot of Occurrence Year without Outliers")

year_occurrence<- table(bt$Occurrence_Year)
year_occurrence<- data.frame(year_occurrence)
colnames(year_occurrence)<- c("Year", "TotalNumber")

ggplot(year_occurrence, aes(x = Year, y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 0), plot.title = element_text(size = 20, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 4.5)+labs(title = "Barplot of Year Occurrence", x = "", y = "Number of Crimes")

# Occurance Month

bt$Occurrence_Month<- as.factor(bt$Occurrence_Month)
levels(bt$Occurrence_Month)
bt$Occurrence_Month<- ordered(bt$Occurrence_Month, levels = c("January", "February", "March", "April","May","June", "July", "August", "September", "October", "November", "December"))
levels(bt$Occurrence_Month)

month_occurrence<- table(bt$Occurrence_Month)
month_occurrence<- data.frame(month_occurrence)
colnames(month_occurrence)<- c("Month", "TotalNumber")

ggplot(month_occurrence, aes(x = Month, y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 0), plot.title = element_text(size = 20, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 4.5)+labs(title = "Barplot of Month of Year Occurrence", x = "", y = "Number of Crimes")


#Year and Month Analysis

year_month<- table(bt$Occurrence_Month, bt$Occurrence_Year)
year_month

January<- c(49, 68, 107, 91, 89, 122, 114)
February<-c(30, 33, 112, 105, 101, 68, 120)
March<-c(58, 97, 147, 139, 132, 118, 185)
April<- c(147, 269, 234, 267, 207, 189, 240)
May<-c(329, 439, 412, 400, 426, 347, 306)
June<-c( 556, 414, 492, 496, 581, 486, 507)
July<-c(558, 501, 513, 552, 644, 612, 622)
August<-c(438, 446, 544, 490, 607, 542, 613)
September<-c(405, 398, 546, 495, 457, 477, 487)
October<-c(272, 278, 338, 446, 387, 414, 357)
November<-c(126, 204, 252, 282, 196, 210, 197)
December<-c(117, 142, 116, 109, 133, 132, 85)



Combined_Months<- data.frame(cbind(January, February, March, April, May, June, July, August, September, October, November, December))
Stacked_Months<- stack(Combined_Months)
summary(Combined_Months)

ggplot(Stacked_Months, aes(ind, values, fill = ind))+geom_boxplot()+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 0), plot.title = element_text(size = 20, hjust = 0.5),legend.title = element_blank())+labs(title = "Boxplot of Monthly Occurrence", x = "Months", y = "Number of Crimes")

Anova_months<- aov(values~ind, data = Stacked_Months)
Anova_months
summary(Anova_months)



#               Day of week

year_week<- table(bt$Occurrence_DayOfWeek, bt$Occurrence_Year)

bt$Occurrence_DayOfWeek<- as.factor(bt$Occurrence_DayOfWeek)
levels(bt$Occurrence_DayOfWeek)
bt$Occurrence_DayOfWeek<- ordered(bt$Occurrence_DayOfWeek, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday","Saturday", "Sunday" ))
levels(bt$Occurrence_DayOfWeek)

days_of_week<- table(bt$Occurrence_DayOfWeek)
days_of_week<- data.frame(days_of_week)
colnames(days_of_week)<- c("Day", "TotalNumber")

ggplot(days_of_week, aes(x = Day, y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text.x = element_text(angle = 0), plot.title = element_text(size = 20, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 4.5)+labs(title = "Barplot of Day of Week Occurrence", x = "", y = "Number of Crimes")



#              Hour of the day


bike_hours<- table(bt$Occurrence_Hour)
bike_hours<- data.frame((bike_hours))
colnames(bike_hours)<- c("Hours", "TotalNumber")

ggplot(bike_hours, aes(x = Hours, y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 0), plot.title = element_text(size = 20, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Hour Occurrence", x = "Hours", y = "Number of Crimes")



#               Division

division<- table(bt$Division)
division<- data.frame(division)
colnames(division)<- c("Division", "TotalNumber")

ggplot(division, aes(x = reorder(Division, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 0), plot.title = element_text(size = 20, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Division", x = "Division", y = "Number of Crimes")


#           Neighbourhoods

hoods<- table(bt$NeighbourhoodName)

hoods<- data.frame(hoods, stringsAsFactors = F)
colnames(hoods)<- c("Name", "TotalNumber")
max_hoods<- filter(hoods, TotalNumber>400)
min_hoods<- filter(hoods, TotalNumber<30)

ggplot(max_hoods, aes(x = reorder(Name, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90), plot.title = element_text(size = 20, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Neighbourhoods which have more than 400 crimes", x = "Neighbourhoods", y = "Number of Crimes")

ggplot(min_hoods, aes(x = reorder(Name, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90), plot.title = element_text(size = 20, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot Neighbourhoods which have less than 30 crimes", x = "Neighbourhoods", y = "Number of Crimes")




#          Location type

location_type<- table(bt$Location_Type)
location_type<- data.frame(location_type)
colnames(location_type)<- c("Type", "TotalNumber")

max_location_type<- filter(location_type, TotalNumber>100)

ggplot(max_location_type, aes(x = reorder(Type, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(axis.text.x = element_text(angle = 90))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "                                    Barplot of Location Types which have more than 100 crimes", x = "Location Types", y = "Number of Crimes")


#        Offence Type

offence_type<- table(bt$Primary_Offence)
offence_type<- data.frame(offence_type)
colnames(offence_type)<- c("Type", "TotalNumber")

max_offence_type<-filter(offence_type, TotalNumber>50)

ggplot(max_offence_type, aes(x = reorder(Type, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90), plot.title = element_text(size = 15, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Offence Types which occured more than 50 times", x = "Primary Offence Type", y = "Number of crimes")

#     Premises Type

table(bt$Premises_Type)

premises_type<- table(bt$Premises_Type)
premises_type<- data.frame(premises_type)
colnames(premises_type)<- c("Type", "TotalNumber")

ggplot(premises_type, aes(x = reorder(Type, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90), plot.title = element_text(size = 15, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Premises Type", x = "Premises Type", y = "Number of Crimes")


piepercent<- round(100*premises_type$TotalNumber/sum(premises_type$TotalNumber), 1)
pie(premises_type$TotalNumber, labels = piepercent, main = "Premises Type Pie Chart (with percentage)", col = rainbow(length(premises_type$TotalNumber)))
legend("topright", c("Apartment","Commercial","Educational","House", "Other", "Outside", "Transit"), cex = 0.8, fill = rainbow(length(premises_type$TotalNumber)))

#              Bike Make

bike_make<- table(bt$Bike_Make)
bike_make<- data.frame(table(bt$Bike_Make))
colnames(bike_make)<- c("Make", "TotalNumber")

max_bike_make<- filter(bike_make, TotalNumber>300)

ggplot(max_bike_make, aes(x = reorder(Make, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90), plot.title = element_text(size = 15, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Most Popular Stolen Bike Makes", x = "Bike Make", y = "Total Number")

# Bike Type

bike_type<- table(bt$Bike_Type)
bike_type<- data.frame(bike_type)
colnames(bike_type)<- c("BikeType", "TotalNumber")

ggplot(bike_type, aes(x = reorder(BikeType, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90), plot.title = element_text(size = 15, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Bike Types", x = "Bike Type", y = "Number of crimes")
#  Cost of the Bike

bike_price<- table(bt$Cost_of_Bike)
bike_price<- data.frame(bike_price)
colnames(bike_price)<- c("Price", "TotalNumber")



ggplot(bike_price, aes(x = reorder(Price, -TotalNumber), y = TotalNumber))+geom_bar(stat = "identity", fill= c("#3260F5"))+theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 90), plot.title = element_text(size = 15, hjust = 0.5))+geom_text(aes(label = TotalNumber), vjust = 1.6, color = "white", size = 3.5)+labs(title = "Barplot of Cost of the Stolen Bike", x = "Cost of the Bikes", y = "Total Number")


#Status
bike_status<-table(bt$Status)
bike_status<- data.frame(bike_status)
colnames(bike_status)<- c("Status", "TotalNumber")

piepercent<- round(100*bike_status$TotalNumber/sum(bike_status$TotalNumber), 1)
pie(bike_status$TotalNumber, labels = piepercent, main = "Pie Chart Status of Stolen Bicycles (with percentage)", col = rainbow(length(bike_status$TotalNumber)))
legend("topright", c("RECOVERED","STOLEN","UNKNOWN"), cex = 0.8, fill = rainbow(length(bike_status$TotalNumber)))

#___________________________________________Statistical analysis________________________________________





#__________________________________________Random forest model__________________________________________


bicycle_theft <- read.csv(file = "bicycle-thefts.csv", header = T, stringsAsFactors = TRUE) #Loading data

str(bicycle_theft)

bt_clean<- bicycle_theft
bt_clean$event_unique_id<- as.character(bt_clean$event_unique_id)
bt_clean$Occurrence_Date<- as.Date(bt_clean$Occurrence_Date)
bt_clean$Report_Date<- as.Date(bt_clean$Report_Date)
bt_clean$Primary_Offence<- as.character(bt_clean$Primary_Offence)
bt_clean$Occurrence_Year<- as.numeric(bt_clean$Occurrence_Year)
bt_clean$Occurrence_Month<- as.factor(bt_clean$Occurrence_Month)
bt_clean$Occurrence_DayOfWeek<- as.factor(bt_clean$Occurrence_DayOfWeek)
bt_clean$Occurrence_Hour<- as.factor(bt_clean$Occurrence_Hour)
bt_clean$Division<- as.factor(bt_clean$Division)
bt_clean$Hood_ID<- as.integer(bt_clean$Hood_ID)
bt_clean$NeighbourhoodName<- as.character(bt_clean$NeighbourhoodName)
bt_clean$Location_Type<- as.factor(bt_clean$Location_Type)
bt_clean$Premises_Type<- as.factor(bt_clean$Premises_Type)
bt_clean$Bike_Make<- as.character(bt_clean$Bike_Make)
bt_clean$Bike_Model<- as.character(bt_clean$Bike_Model)
bt_clean$Bike_Type<- as.factor(bt_clean$Bike_Type)
bt_clean$Cost_of_Bike<- as.numeric(bt_clean$Cost_of_Bike)
bt_clean$Status<- as.factor(bt_clean$Status)
bt_clean$Bike_Colour<-as.character(bt_clean$Bike_Colour)
str(bt_clean)


#Reducing the levels of rating for Neigbourhood based on quantile

Neighbourhoods<- table(bt_clean$NeighbourhoodName)
Neighbourhoods<- data.frame(Neighbourhoods, stringsAsFactors = F)
colnames(Neighbourhoods)<- c("NeighbourhoodName", "TotalNumber")

quantcut(Neighbourhoods$TotalNumber, 5)

Neighbourhoods$Hood_Risk<- ifelse(Neighbourhoods$TotalNumber<26, "Very Low", ifelse(Neighbourhoods$TotalNumber<49, "Low", ifelse(Neighbourhoods$TotalNumber<94, "Medium", ifelse(Neighbourhoods$TotalNumber<221, "High", "Very High"))))
Neighbourhoods_subset<- subset(Neighbourhoods, select = -TotalNumber)
bt_clean<- merge(bt_clean, Neighbourhoods_subset, by = "NeighbourhoodName")
bt_clean$Hood_Risk<- as.factor(bt_clean$Hood_Risk)
bt_clean$Hood_Risk<- ordered(bt_clean$Hood_Risk, c('Very Low', 'Low', 'Medium', 'High', 'Very High'))
table(Neighbourhoods$Hood_Risk)



#Future Selection Chi-Squared


bt_clean_future_selection<- subset(bt_clean, select = -c(X_id,OBJECTID, event_unique_id,Occurrence_DayOfMonth,Occurrence_DayOfYear, Report_Date, Report_Year, Report_Month, Report_DayOfWeek, Report_DayOfMonth, Report_DayOfYear, Report_Hour, Bike_Speed, ObjectId2, geometry))

weights<- chi.squared(Hood_Risk~., bt_clean_future_selection)
print(weights)
subset<- cutoff.k(weights, 18)
f<- as.simple.formula(subset, "Hood_Risk")
print(f)



#__________________________________Method_1 Repeated cross-validation

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl_1<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
model_1_1<- randomForest(Hood_Risk~., data = data_1_train, ntree = 100, trainControl = ctrl_1, tuneLength = 5)
print(model_1_1)
plot(model_1_1)

#Testing Model
risk_pred_model_1_1<- predict(model_1_1, data_1_test)

#t<- tuneRF(data_1_train[,-18], data_1_train[,18], stepFactor = 0.5, plot = TRUE, ntreeTry = 200, trace = TRUE, improve = 0.05)
#plot(t)

#Statistics about model
data_1_test$risk_pred_model_1_1<- risk_pred_model_1_1
conf_matrix_rfm_1_1<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_model_1_1)
conf_matrix_rfm_1_1
class_accuarcy_model_1_1<- sum(diag(conf_matrix_rfm_1_1)/sum(conf_matrix_rfm_1_1))
class_accuarcy_model_1_1
confusionMatrix(conf_matrix_rfm_1_1)

hist(treesize(model_1_1), main = "Number of Nodes for the Trees", col = "green")
varImpPlot(model_1_1, sort = TRUE, main = "Variable Importance")
importance(model_1_1)


#_______________________________________________Method_2 Leave one out cross validation - LOOCV

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl_2<- trainControl(method = "LOCV")


#Building model
model_1_2<- randomForest(Hood_Risk~., data = data_1_train, ntree = 100, trainControl = ctrl_2, tuneLength = 5)
print(model_1_2)
plot(model_1_2)

#Testing Model
risk_pred_model_1_2<- predict(model_1_2, data_1_test)


#Statistics about model
data_1_test$risk_pred_model_1_2<- risk_pred_model_1_2
conf_matrix_rfm_1_2<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_model_1_2)
conf_matrix_rfm_1_2
class_accuarcy_model_1_2<- sum(diag(conf_matrix_rfm_1_2)/sum(conf_matrix_rfm_1_2))
class_accuarcy_model_1_2
confusionMatrix(conf_matrix_rfm_1_2)

hist(treesize(model_1_2), main = "Number of Nodes for the Trees", col = "green")
varImpPlot(model_1_2, sort = TRUE, main = "Variable Importance")
importance(model_1_2)


#_____________________________________________Method_3 K-fold cross-validation
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl_3<- trainControl(method = "cv", number = 10)

#Building model
model_1_3<- randomForest(Hood_Risk~., data = data_1_train, ntree = 100, trainControl = ctrl_3, tuneLength = 5)
print(model_1_3)
plot(model_1_3)

#Testing Model
risk_pred_model_1_3<- predict(model_1_3, data_1_test)



#Statistics about model
data_1_test$risk_pred_model_1_3<- risk_pred_model_1_3
conf_matrix_rfm_1_3<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_model_1_3)
conf_matrix_rfm_1_3
class_accuarcy_model_1_3<- sum(diag(conf_matrix_rfm_1_3)/sum(conf_matrix_rfm_1_3))
class_accuarcy_model_1_3
confusionMatrix(conf_matrix_rfm_1_3)

hist(treesize(model_1_3), main = "Number of Nodes for the Trees", col = "green")
varImpPlot(model_1_3, sort = TRUE, main = "Variable Importance")
importance(model_1_3)


#During comparing 3 method cv model accurracies were same we will use repeated k-fold cross-validation on random forest using different features




#_______________NOW we will perform different features(variable combinations) on Random Forest______________________

#All features

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_01<- randomForest(Hood_Risk~., data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_01)
plot(rf_model_01)

#Testing Model
risk_pred_rf_model_01<- predict(rf_model_01, data_1_test)

#t<- tuneRF(data_1_train[,-18], data_1_train[,18], stepFactor = 0.5, plot = TRUE, ntreeTry = 200, trace = TRUE, improve = 0.05)
#plot(t)

#Statistics about model
data_1_test$risk_pred_rf_model_01<- risk_pred_rf_model_01
conf_matrix_rf_model_01<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_01)
conf_matrix_rf_model_01
class_accuarcy_rf_model_01<- sum(diag(conf_matrix_rf_model_01)/sum(conf_matrix_rf_model_01))
class_accuarcy_rf_model_01
confusionMatrix(conf_matrix_rf_model_01)

hist(treesize(rf_model_01),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_01, sort = TRUE, main = "Variable Importance")
importance(rf_model_01)




#__________No Status and City feature

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_02<- randomForest(Hood_Risk~.-Status-City, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_02)
plot(rf_model_02)

#Testing Model
risk_pred_rf_model_02<- predict(rf_model_02, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_02<- risk_pred_rf_model_02
conf_matrix_rf_model_02<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_02)
conf_matrix_rf_model_02
class_accuarcy_rf_model_02<- sum(diag(conf_matrix_rf_model_02)/sum(conf_matrix_rf_model_02))
class_accuarcy_rf_model_02
confusionMatrix(conf_matrix_rf_model_02)

hist(treesize(rf_model_02),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_02, sort = TRUE, main = "Variable Importance")
importance(rf_model_02)


#_____________No Status No City No Primary_Offence

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_03<- randomForest(Hood_Risk~.-Status-City-Primary_Offence, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_03)
plot(rf_model_03)

#Testing Model
risk_pred_rf_model_03<- predict(rf_model_03, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_03<- risk_pred_rf_model_03
conf_matrix_rf_model_03<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_03)
conf_matrix_rf_model_03
class_accuarcy_rf_model_03<- sum(diag(conf_matrix_rf_model_03)/sum(conf_matrix_rf_model_03))
class_accuarcy_rf_model_03
confusionMatrix(conf_matrix_rf_model_03)

hist(treesize(rf_model_03),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_03, sort = TRUE, main = "Variable Importance")
importance(rf_model_03)


#_____________No Status No City No Primary_Offence No Occurrence_Year

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_04<- randomForest(Hood_Risk~.-Status-City-Primary_Offence-Occurrence_Year, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_04)
plot(rf_model_04)

#Testing Model
risk_pred_rf_model_04<- predict(rf_model_04, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_04<- risk_pred_rf_model_04
conf_matrix_rf_model_04<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_04)
conf_matrix_rf_model_04
class_accuarcy_rf_model_04<- sum(diag(conf_matrix_rf_model_04)/sum(conf_matrix_rf_model_04))
class_accuarcy_rf_model_04
confusionMatrix(conf_matrix_rf_model_04)

hist(treesize(rf_model_04),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_04, sort = TRUE, main = "Variable Importance")
importance(rf_model_04)



#_____________No Status No City No Primary_Offence No Occurrence_Year No Premises_Type No Bike_Model

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_05<- randomForest(Hood_Risk~.-Status-City-Primary_Offence-Occurrence_Year-Premises_Type-Bike_Model, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_05)
plot(rf_model_05)

#Testing Model
risk_pred_rf_model_05<- predict(rf_model_05, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_05<- risk_pred_rf_model_05
conf_matrix_rf_model_05<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_05)
conf_matrix_rf_model_05
class_accuarcy_rf_model_05<- sum(diag(conf_matrix_rf_model_05)/sum(conf_matrix_rf_model_05))
class_accuarcy_rf_model_05
confusionMatrix(conf_matrix_rf_model_05)

hist(treesize(rf_model_05),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_05, sort = TRUE, main = "Variable Importance")
importance(rf_model_05)


#_____________No Status No City No Primary_Offence No Occurrence_Year No Premises_Type No Bike_Model No Bike_Colour

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_06<- randomForest(Hood_Risk~.-Status-City-Primary_Offence-Occurrence_Year-Premises_Type-Bike_Model-Bike_Colour, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_06)
plot(rf_model_06)

#Testing Model
risk_pred_rf_model_06<- predict(rf_model_06, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_06<- risk_pred_rf_model_06
conf_matrix_rf_model_06<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_06)
conf_matrix_rf_model_06
class_accuarcy_rf_model_06<- sum(diag(conf_matrix_rf_model_06)/sum(conf_matrix_rf_model_06))
class_accuarcy_rf_model_06
confusionMatrix(conf_matrix_rf_model_06)

hist(treesize(rf_model_06),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_06, sort = TRUE, main = "Variable Importance")
importance(rf_model_06)



#_____________No Status No City No Primary_Offence No Occurrence_Year No Premises_Type No Bike_Model No Bike_Colour Bike_Type No Bike

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_07<- randomForest(Hood_Risk~.-Status-City-Primary_Offence-Occurrence_Year-Premises_Type-Bike_Model-Bike_Colour-Bike_Type-Bike_Make, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_07)
plot(rf_model_07)

#Testing Model
risk_pred_rf_model_07<- predict(rf_model_07, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_07<- risk_pred_rf_model_07
conf_matrix_rf_model_07<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_07)
conf_matrix_rf_model_07
class_accuarcy_rf_model_07<- sum(diag(conf_matrix_rf_model_07)/sum(conf_matrix_rf_model_07))
class_accuarcy_rf_model_07
confusionMatrix(conf_matrix_rf_model_07)

hist(treesize(rf_model_07),ylim = c(0, 35) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "yellow") 
varImpPlot(rf_model_07, sort = TRUE, main = "Variable Importance")
importance(rf_model_07)

n_conf_matrix_rf_model_07 = sum(conf_matrix_rf_model_07)
nc_conf_matrix_rf_model_07 = nrow(conf_matrix_rf_model_07)
diag_conf_matrix_rf_model_07 = diag(conf_matrix_rf_model_07)
rowsums_conf_matrix_rf_model_07 = apply(conf_matrix_rf_model_07, 1, sum)
colsums_conf_matrix_rf_model_07 = apply(conf_matrix_rf_model_07, 2, sum)

precision_conf_matrix_rf_model_07 = diag_conf_matrix_rf_model_07 / colsums_conf_matrix_rf_model_07 
recall_conf_matrix_rf_model_07 = diag_conf_matrix_rf_model_07 / rowsums_conf_matrix_rf_model_07 
f1_conf_matrix_rf_model_07 = 2 * precision_conf_matrix_rf_model_07 * recall_conf_matrix_rf_model_07 / (precision_conf_matrix_rf_model_07 + recall_conf_matrix_rf_model_07) 
data_frame_conf_matrix_rf_model_07<- data.frame(precision_conf_matrix_rf_model_07, recall_conf_matrix_rf_model_07, f1_conf_matrix_rf_model_07)
data_frame_conf_matrix_rf_model_07

#_____________No Division

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_08<- randomForest(Hood_Risk~.-Division, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_08)
plot(rf_model_08)

#Testing Model
risk_pred_rf_model_08<- predict(rf_model_08, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_08<- risk_pred_rf_model_08
conf_matrix_rf_model_08<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_08)
conf_matrix_rf_model_08
class_accuarcy_rf_model_08<- sum(diag(conf_matrix_rf_model_08)/sum(conf_matrix_rf_model_08))
class_accuarcy_rf_model_08
confusionMatrix(conf_matrix_rf_model_08)

hist(treesize(rf_model_08),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_08, sort = TRUE, main = "Variable Importance")
importance(rf_model_08)


#_____________No NeighbourhoodName

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_09<- randomForest(Hood_Risk~.-NeighbourhoodName, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_09)
plot(rf_model_09)

#Testing Model
risk_pred_rf_model_09<- predict(rf_model_09, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_09<- risk_pred_rf_model_09
conf_matrix_rf_model_09<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_09)
conf_matrix_rf_model_09
class_accuarcy_rf_model_09<- sum(diag(conf_matrix_rf_model_09)/sum(conf_matrix_rf_model_09))
class_accuarcy_rf_model_09
confusionMatrix(conf_matrix_rf_model_09)

hist(treesize(rf_model_09),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_09, sort = TRUE, main = "Variable Importance")
importance(rf_model_09)


#_____________No NeighbourhoodName and No Division

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_10<- randomForest(Hood_Risk~.-NeighbourhoodName-Division, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_10)
plot(rf_model_10)

#Testing Model
risk_pred_rf_model_10<- predict(rf_model_10, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_10<- risk_pred_rf_model_10
conf_matrix_rf_model_10<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_10)
conf_matrix_rf_model_10
class_accuarcy_rf_model_10<- sum(diag(conf_matrix_rf_model_10)/sum(conf_matrix_rf_model_10))
class_accuarcy_rf_model_10
confusionMatrix(conf_matrix_rf_model_10)

hist(treesize(rf_model_10),ylim = c(0, 20) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_10, sort = TRUE, main = "Variable Importance")
importance(rf_model_10)


#_____________No NeighbourhoodName and No Division Hood_ID

set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

#Building model
rf_model_11<- randomForest(Hood_Risk~.-Hood_ID-NeighbourhoodName-Division, data = data_1_train, ntree = 100, trainControl = ctrl, tuneLength = 50)
print(rf_model_11)
plot(rf_model_11)

#Testing Model
risk_pred_rf_model_11<- predict(rf_model_11, data_1_test)


#Statistics about model
data_1_test$risk_pred_rf_model_11<- risk_pred_rf_model_11
conf_matrix_rf_model_11<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_rf_model_11)
conf_matrix_rf_model_11
class_accuarcy_rf_model_11<- sum(diag(conf_matrix_rf_model_11)/sum(conf_matrix_rf_model_11))
class_accuarcy_rf_model_11
confusionMatrix(conf_matrix_rf_model_11)

hist(treesize(rf_model_11),ylim = c(0, 35) ,xlab = "Number of Nodes", ylab = "Number of Trees", main = "Number of Nodes for the Trees", col = "blue")
varImpPlot(rf_model_11, sort = TRUE, main = "Variable Importance")
importance(rf_model_11)

n_conf_matrix_rf_model_11 = sum(conf_matrix_rf_model_11)
nc_conf_matrix_rf_model_11 = nrow(conf_matrix_rf_model_11)
diag_conf_matrix_rf_model_11 = diag(conf_matrix_rf_model_11)
rowsums_conf_matrix_rf_model_11 = apply(conf_matrix_rf_model_11, 1, sum)
colsums_conf_matrix_rf_model_11 = apply(conf_matrix_rf_model_11, 2, sum)

precision_conf_matrix_rf_model_11 = diag_conf_matrix_rf_model_11 / colsums_conf_matrix_rf_model_11 
recall_conf_matrix_rf_model_11 = diag_conf_matrix_rf_model_11 / rowsums_conf_matrix_rf_model_11 
f1_conf_matrix_rf_model_11 = 2 * precision_conf_matrix_rf_model_11 * recall_conf_matrix_rf_model_11 / (precision_conf_matrix_rf_model_11 + recall_conf_matrix_rf_model_11) 
data_frame_conf_matrix_rf_model_11<- data.frame(precision_conf_matrix_rf_model_11, recall_conf_matrix_rf_model_11, f1_conf_matrix_rf_model_11)
data_frame_conf_matrix_rf_model_11


#comparing models according class accuracy

class_rf_models<- data.frame(class_accuarcy_rf_model_01, class_accuarcy_rf_model_02, class_accuarcy_rf_model_03, class_accuarcy_rf_model_04, class_accuarcy_rf_model_05, class_accuarcy_rf_model_06, class_accuarcy_rf_model_07, class_accuarcy_rf_model_08, class_accuarcy_rf_model_09, class_accuarcy_rf_model_10, class_accuarcy_rf_model_11)
boxplot(class_rf_models, xlab = "Models", ylab = "Class Accuracy", main = "Comparing Class Accuracy of Random Forest Models")

boxplot(class_rf_models, xlab = "Models", ylab = "Accuracy", main = "Comparing Accuracy of Random Forest Models")




#__________________________________________Decision TREE model_____________________________________________________


bicycle_theft <- read.csv(file = "bicycle-thefts.csv", header = T, stringsAsFactors = TRUE) #Loading data

str(bicycle_theft)

bt_clean<- bicycle_theft
bt_clean$event_unique_id<- as.character(bt_clean$event_unique_id)
bt_clean$Occurrence_Date<- as.Date(bt_clean$Occurrence_Date)
bt_clean$Report_Date<- as.Date(bt_clean$Report_Date)
bt_clean$Primary_Offence<- as.character(bt_clean$Primary_Offence)
bt_clean$Occurrence_Year<- as.numeric(bt_clean$Occurrence_Year)
bt_clean$Occurrence_Month<- as.factor(bt_clean$Occurrence_Month)
bt_clean$Occurrence_DayOfWeek<- as.factor(bt_clean$Occurrence_DayOfWeek)
bt_clean$Occurrence_Hour<- as.factor(bt_clean$Occurrence_Hour)
bt_clean$Division<- as.factor(bt_clean$Division)
bt_clean$Hood_ID<- as.integer(bt_clean$Hood_ID)
bt_clean$NeighbourhoodName<- as.character(bt_clean$NeighbourhoodName)
bt_clean$Location_Type<- as.factor(bt_clean$Location_Type)
bt_clean$Premises_Type<- as.factor(bt_clean$Premises_Type)
bt_clean$Bike_Make<- as.character(bt_clean$Bike_Make)
bt_clean$Bike_Model<- as.character(bt_clean$Bike_Model)
bt_clean$Bike_Type<- as.factor(bt_clean$Bike_Type)
bt_clean$Cost_of_Bike<- as.numeric(bt_clean$Cost_of_Bike)
bt_clean$Status<- as.factor(bt_clean$Status)
bt_clean$Bike_Colour<-as.character(bt_clean$Bike_Colour)
str(bt_clean)


#Reducing the levels of rating for Neigbourhood based on quantile

Neighbourhoods<- table(bt_clean$NeighbourhoodName)
Neighbourhoods<- data.frame(Neighbourhoods, stringsAsFactors = F)
colnames(Neighbourhoods)<- c("NeighbourhoodName", "TotalNumber")

quantcut(Neighbourhoods$TotalNumber, 5)

Neighbourhoods$Hood_Risk<- ifelse(Neighbourhoods$TotalNumber<26, "Very Low", ifelse(Neighbourhoods$TotalNumber<49, "Low", ifelse(Neighbourhoods$TotalNumber<94, "Medium", ifelse(Neighbourhoods$TotalNumber<221, "High", "Very High"))))
Neighbourhoods_subset<- subset(Neighbourhoods, select = -TotalNumber)
bt_clean<- merge(bt_clean, Neighbourhoods_subset, by = "NeighbourhoodName")
bt_clean$Hood_Risk<- as.factor(bt_clean$Hood_Risk)
bt_clean$Hood_Risk<- ordered(bt_clean$Hood_Risk, c('Very Low', 'Low', 'Medium', 'High', 'Very High'))
table(Neighbourhoods$Hood_Risk)



#Future Selection Chi-Squared


bt_clean_future_selection<- subset(bt_clean, select = -c(X_id,OBJECTID, event_unique_id,Occurrence_DayOfMonth,Occurrence_DayOfYear, Report_Date, Report_Year, Report_Month, Report_DayOfWeek, Report_DayOfMonth, Report_DayOfYear, Report_Hour, Bike_Speed, ObjectId2, geometry))

weights<- chi.squared(Hood_Risk~., bt_clean_future_selection)
print(weights)
subset<- cutoff.k(weights, 18)
f<- as.simple.formula(subset, "Hood_Risk")
print(f)

#Based on variable importance from Random Forest we will use features to buil our tree model on different features




#Building model
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_01 <- train(Hood_Risk ~ Hood_ID + Division + NeighbourhoodName + Occurrence_Hour + Location_Type+Occurrence_Month + Occurrence_Date + Occurrence_DayOfWeek + Premises_Type, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_01)
plot(tree_model_01)

#Testing Model
risk_pred_tree_model_01<- predict(tree_model_01, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_01<- risk_pred_tree_model_01
conf_matrix_tree_model_01<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_01)
conf_matrix_tree_model_01
class_accuarcy_tree_model_01<- sum(diag(conf_matrix_tree_model_01)/sum(conf_matrix_tree_model_01))
class_accuarcy_tree_model_01
confusionMatrix(conf_matrix_tree_model_01)

n_conf_matrix_tree_model_01 = sum(conf_matrix_tree_model_01)
nc_conf_matrix_tree_model_01 = nrow(conf_matrix_tree_model_01)
diag_conf_matrix_tree_model_01 = diag(conf_matrix_tree_model_01)
rowsums_conf_matrix_tree_model_01 = apply(conf_matrix_tree_model_01, 1, sum)
colsums_conf_matrix_tree_model_01 = apply(conf_matrix_tree_model_01, 2, sum)

precision_conf_matrix_tree_model_01 = diag_conf_matrix_tree_model_01 / colsums_conf_matrix_tree_model_01 
recall_conf_matrix_tree_model_01 = diag_conf_matrix_tree_model_01 / rowsums_conf_matrix_tree_model_01 
f1_conf_matrix_tree_model_01 = 2 * precision_conf_matrix_tree_model_01 * recall_conf_matrix_tree_model_01 / (precision_conf_matrix_tree_model_01 + recall_conf_matrix_tree_model_01) 
data_frame_conf_matrix_tree_model_01<- data.frame(precision_conf_matrix_tree_model_01, recall_conf_matrix_tree_model_01, f1_conf_matrix_tree_model_01)
data_frame_conf_matrix_tree_model_01




#No Premises_Type__________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_02 <- train(Hood_Risk ~ Hood_ID + Division + NeighbourhoodName + Occurrence_Hour + Location_Type+Occurrence_Month + Occurrence_Date + Occurrence_DayOfWeek, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_02)
plot(tree_model_02)

#Testing Model
risk_pred_tree_model_02<- predict(tree_model_02, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_02<- risk_pred_tree_model_02
conf_matrix_tree_model_02<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_02)
conf_matrix_tree_model_02
class_accuarcy_tree_model_02<- sum(diag(conf_matrix_tree_model_02)/sum(conf_matrix_tree_model_02))
class_accuarcy_tree_model_02
confusionMatrix(conf_matrix_tree_model_02)

#No Premises_Type+Occurrence_DayOfWeek__________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_03 <- train(Hood_Risk ~ Hood_ID + Division + NeighbourhoodName + Occurrence_Hour + Location_Type+Occurrence_Month + Occurrence_Date, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_03)
plot(tree_model_03)

#Testing Model
risk_pred_tree_model_03<- predict(tree_model_03, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_03<- risk_pred_tree_model_03
conf_matrix_tree_model_03<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_03)
conf_matrix_tree_model_03
class_accuarcy_tree_model_03<- sum(diag(conf_matrix_tree_model_03)/sum(conf_matrix_tree_model_03))
class_accuarcy_tree_model_03
confusionMatrix(conf_matrix_tree_model_03)

#No Premises_Type+Occurrence_DayOfWeek+Occurrence_Date__________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_04 <- train(Hood_Risk ~ Hood_ID + Division + NeighbourhoodName + Occurrence_Hour + Location_Type+Occurrence_Month, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_04)
plot(tree_model_04)

#Testing Model
risk_pred_tree_model_04<- predict(tree_model_04, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_04<- risk_pred_tree_model_04
conf_matrix_tree_model_04<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_04)
conf_matrix_tree_model_04
class_accuarcy_tree_model_04<- sum(diag(conf_matrix_tree_model_04)/sum(conf_matrix_tree_model_04))
class_accuarcy_tree_model_04
confusionMatrix(conf_matrix_tree_model_04)

#No Premises_Type+Occurrence_DayOfWeek+Occurrence_Date+Occurrence_Month__________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_05 <- train(Hood_Risk ~ Hood_ID + Division + NeighbourhoodName + Occurrence_Hour + Location_Type, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_05)
plot(tree_model_05)

#Testing Model
risk_pred_tree_model_05<- predict(tree_model_05, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_05<- risk_pred_tree_model_05
conf_matrix_tree_model_05<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_05)
conf_matrix_tree_model_05
class_accuarcy_tree_model_05<- sum(diag(conf_matrix_tree_model_05)/sum(conf_matrix_tree_model_05))
class_accuarcy_tree_model_05
confusionMatrix(conf_matrix_tree_model_05)

#No Premises_Type+Occurrence_DayOfWeek+Occurrence_Date+Occurrence_Month + Location_Type__________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_06 <- train(Hood_Risk ~ Hood_ID + Division + NeighbourhoodName + Occurrence_Hour, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_06)
plot(tree_model_06)

#Testing Model
risk_pred_tree_model_06<- predict(tree_model_06, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_06<- risk_pred_tree_model_06
conf_matrix_tree_model_06<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_06)
conf_matrix_tree_model_06
class_accuarcy_tree_model_06<- sum(diag(conf_matrix_tree_model_06)/sum(conf_matrix_tree_model_06))
class_accuarcy_tree_model_06
confusionMatrix(conf_matrix_tree_model_06)

#___No_Hood_ID NO Division No Neighbourhood
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_07 <- train(Hood_Risk ~ Occurrence_Hour + Location_Type+Occurrence_Month + Occurrence_Date + Occurrence_DayOfWeek + Premises_Type, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_07)
plot(tree_model_07, main = "Accuracy and Complexity of Decision Model 7")

#Testing Model
risk_pred_tree_model_07<- predict(tree_model_07, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_07<- risk_pred_tree_model_07
conf_matrix_tree_model_07<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_07)
conf_matrix_tree_model_07
class_accuarcy_tree_model_07<- sum(diag(conf_matrix_tree_model_07)/sum(conf_matrix_tree_model_07))
class_accuarcy_tree_model_07
confusionMatrix(conf_matrix_tree_model_07)

n_conf_matrix_tree_model_07 = sum(conf_matrix_tree_model_07)
nc_conf_matrix_tree_model_07 = nrow(conf_matrix_tree_model_07)
diag_conf_matrix_tree_model_07 = diag(conf_matrix_tree_model_07)
rowsums_conf_matrix_tree_model_07 = apply(conf_matrix_tree_model_07, 1, sum)
colsums_conf_matrix_tree_model_07 = apply(conf_matrix_tree_model_07, 2, sum)

precision_conf_matrix_tree_model_07 = diag_conf_matrix_tree_model_07 / colsums_conf_matrix_tree_model_07 
recall_conf_matrix_tree_model_07 = diag_conf_matrix_tree_model_07 / rowsums_conf_matrix_tree_model_07 
f1_conf_matrix_tree_model_07 = 2 * precision_conf_matrix_tree_model_07 * recall_conf_matrix_tree_model_07 / (precision_conf_matrix_tree_model_07 + recall_conf_matrix_tree_model_07) 
data_frame_conf_matrix_tree_model_07<- data.frame(precision_conf_matrix_tree_model_07, recall_conf_matrix_tree_model_07, f1_conf_matrix_tree_model_07)
data_frame_conf_matrix_tree_model_07




#No Premises_Type+Occurrence_DayOfWeek+Occurrence_Date+Occurrence_Month + Location_Type + Occurrence_Hour + NeighbourhoodName__________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_08 <- train(Hood_Risk ~ Hood_ID + Division, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_08)
plot(tree_model_08)

#Testing Model
risk_pred_tree_model_08<- predict(tree_model_08, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_08<- risk_pred_tree_model_08
conf_matrix_tree_model_08<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_08)
conf_matrix_tree_model_08
class_accuarcy_tree_model_08<- sum(diag(conf_matrix_tree_model_08)/sum(conf_matrix_tree_model_08))
class_accuarcy_tree_model_08
confusionMatrix(conf_matrix_tree_model_08)

#No Premises_Type+Occurrence_DayOfWeek+Occurrence_Date+Occurrence_Month + Location_Type + Occurrence_Hour + Hood_ID  __________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_09 <- train(Hood_Risk ~ NeighbourhoodName + Division, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_09)
plot(tree_model_09)

#Testing Model
risk_pred_tree_model_09<- predict(tree_model_09, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_09<- risk_pred_tree_model_09
conf_matrix_tree_model_09<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_09)
conf_matrix_tree_model_09
class_accuarcy_tree_model_09<- sum(diag(conf_matrix_tree_model_09)/sum(conf_matrix_tree_model_09))
class_accuarcy_tree_model_09
confusionMatrix(conf_matrix_tree_model_09)

#No Premises_Type+Occurrence_DayOfWeek+Occurrence_Date+Occurrence_Month + Occurrence_Hour + Hood_ID  __________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_10 <- train(Hood_Risk ~ NeighbourhoodName + Location_Type, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_10)
plot(tree_model_10)

#Testing Model
risk_pred_tree_model_10<- predict(tree_model_10, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_10<- risk_pred_tree_model_10
conf_matrix_tree_model_10<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_10)
conf_matrix_tree_model_10
class_accuarcy_tree_model_10<- sum(diag(conf_matrix_tree_model_10)/sum(conf_matrix_tree_model_10))
class_accuarcy_tree_model_10
confusionMatrix(conf_matrix_tree_model_10)



#No Premises_Type+Occurrence_DayOfWeek+Occurrence_Date+Occurrence_Month + Hood_ID  __________________________
set.seed(999)
data_1<- bt_clean_future_selection

#Random Sampling
Index<- sample(nrow(data_1), floor(0.70*nrow(data_1)))
data_1_train<- data_1[Index,]
data_1_test<- data_1[-Index,]

#Treating train data
data_1_train$Cost_of_Bike[is.na(data_1_train$Cost_of_Bike)]<- mean(data_1_train$Cost_of_Bike,na.rm=TRUE)
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2009] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2010] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2011] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2012] <- 2014
data_1_train$Occurrence_Year[data_1_train$Occurrence_Year==2013] <- 2014

ctrl<- trainControl(method = "repeatedcv", number = 10 ,repeats = 10)

tree_model_11 <- train(Hood_Risk ~ NeighbourhoodName + Location_Type + Occurrence_Hour, data = data_1_train, method = "rpart", trControl = ctrl, tuneLength = 50)

print(tree_model_11)
plot(tree_model_11)

#Testing Model
risk_pred_tree_model_11<- predict(tree_model_11, data_1_test)


#Statistics about model
data_1_test$risk_pred_tree_model_11<- risk_pred_tree_model_11
conf_matrix_tree_model_11<- table(data_1_test$Hood_Risk, data_1_test$risk_pred_tree_model_11)
conf_matrix_tree_model_11
class_accuarcy_tree_model_11<- sum(diag(conf_matrix_tree_model_11)/sum(conf_matrix_tree_model_11))
class_accuarcy_tree_model_11
confusionMatrix(conf_matrix_tree_model_11)



#tree class comparing
class_accurracy_tree_model<- data.frame(class_accuarcy_tree_model_01, class_accuarcy_tree_model_02, class_accuarcy_tree_model_03, class_accuarcy_tree_model_04, class_accuarcy_tree_model_05, class_accuarcy_tree_model_06, class_accuarcy_tree_model_07, class_accuarcy_tree_model_08, class_accuarcy_tree_model_09, class_accuarcy_tree_model_10, class_accuarcy_tree_model_11)
class_accurracy_tree_model

boxplot(class_accurracy_tree_model, xlab = "Models", ylab = "Accuracy", main = "Comparing Accuracy of Decision Tree Models")



